version: '3.7'

services:
  php-8-fpm:
    image: php:8-fpm
    tty: true
    volumes:
      - ./:/${PROJECT_NAME}

  php-7.4-fpm:
    image: php:7.4-fpm
    tty: true
    volumes:
      - ./:/${PROJECT_NAME}
